### ISSUE TITLE
Create room

### ISSUE THREAD

**Issue by yuval9313** [DawnOfHell/Ongaku#7]

**Comment by yuval9313** [comment]
Rooms API:

## Create new room
POST `/rooms`
{"manager": str}
*Return*
{"room_id": str}

## Get details of room - might be websocket
GET `/rooms/{room_id}`
*Return*
{"members": List[Player], "scoreboard": Scoreboard, "room_id": str}

## ? Remove room - Should user have the ability to remove rooms?
DELETE `/rooms/{room_id}`
*Return*
{"room_id": str}

## Update room manager
PATCH `/rooms/{room_id}`
{"manager": str}
*Return*
{"room_id": str, "manager": str}

**Comment by yuval9313** [comment]
## Get room members
GET `/rooms/{room_id}/members`
*Return*
{"members": List[Player]}

## Get room members
GET `/rooms/{room_id}/scoreboard`
*Return*
{"scoreboard": scoreboard}

This approach means that scoreboard and members are both resources of room

**Comment by DawnOfHell** [comment]
updating the room manager should happend automaticly-

POST /rooms/exit_room/{exit_room}
if is the manager will select new manager

**Comment by yuval9313** [comment]
If user exit the tab the server will elect new leader and remove the dead websockets from the members

I think it is more REST-y to do as follows
## Disconnect player from room
```
DELETE `/rooms/{room_id}/members/{member_id}`
*Returns*
{"room_id": str}
```
